Style/Documentation: 
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Security/YAMLLoad:
  Exclude:
    - lib/modules/storage.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/game_core_spec.rb